/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 60362d6e7cc0c568e2efb27e2682d333)
interface __BaseEnv_Env {
	GENIE_APP: DurableObjectNamespace<import("./cloudflare/worker").GenieContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/worker");
		durableNamespaces: "GenieContainer";
	}
	interface ProductionEnv {
		GENIE_APP: DurableObjectNamespace<import("./cloudflare/worker").GenieContainer>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
