// ============================================================================
// COMPREHENSIVE CAKE SEARCH KEYWORDS DATABASE
// Updated: 2024-2025 Trends
// Total: 500+ Keywords
// ============================================================================

export const CAKE_SEARCH_KEYWORDS = [
  
  // ========== OCCASIONS (Most Popular) ==========
  'birthday cake',
  'wedding cake',
  'anniversary cake',
  'graduation cake',
  'baby shower cake',
  'bridal shower cake',
  'retirement cake',
  'engagement cake',
  'christening cake',
  'baptism cake',
  'first communion cake',
  'confirmation cake',
  'gender reveal cake',
  
  // ========== POPULAR CHARACTERS & CLASSIC THEMES ==========
  'unicorn cake',
  'dinosaur cake',
  'princess cake',
  'spiderman cake',
  'batman cake',
  'frozen cake',
  'elsa cake',
  'anna cake',
  'paw patrol cake',
  'cocomelon cake',
  'minecraft cake',
  'roblox cake',
  'among us cake',
  'pokemon cake',
  'pikachu cake',
  'hello kitty cake',
  'barbie cake',
  'disney princess cake',
  'avengers cake',
  'iron man cake',
  'captain america cake',
  'hulk cake',
  'mermaid cake',
  'fairy cake',
  'superhero cake',
  'mickey mouse cake',
  'minnie mouse cake',
  'peppa pig cake',
  'bluey cake',
  
  // ========== ANIME & MANGA ==========
  'naruto cake',
  'luffy cake',
  'one piece cake',
  'goku cake',
  'dragon ball cake',
  'demon slayer cake',
  'tanjiro cake',
  'nezuko cake',
  'jujutsu kaisen cake',
  'gojo cake',
  'sukuna cake',
  'attack on titan cake',
  'spy family cake',
  'anya cake',
  'my hero academia cake',
  'deku cake',
  'sailor moon cake',
  'totoro cake',
  'ghibli cake',
  'spirited away cake',
  'hunter x hunter cake',
  'haikyuu cake',
  'tokyo ghoul cake',
  'My Neighbor Totoro cake',
  'No Face cake',
  
  // ========== VIDEO GAMES ==========
  'fortnite cake',
  'call of duty cake',
  'valorant cake',
  'apex legends cake',
  'overwatch cake',
  'league of legends cake',
  'genshin impact cake',
  'sonic cake',
  'mario cake',
  'zelda cake',
  'animal crossing cake',
  'splatoon cake',
  'gaming cake',
  'video game cake',
  
  // ========== MUSIC & CELEBRITIES ==========
  'taylor swift cake',
  'eras tour cake',
  'swiftie cake',
  'beyonce cake',
  'ariana grande cake',
  'billie eilish cake',
  'olivia rodrigo cake',
  'sabrina carpenter cake',
  'bad bunny cake',
  'drake cake',
  'the weeknd cake',
  'bruno mars cake',
  'post malone cake',
  'travis scott cake',
  'music note cake',
  'record player cake',
  'vinyl cake',
  'microphone cake',
  'concert cake',
  'festival cake',
  'rock band cake',
  'music cake',
  'guitar cake',
  'piano cake',
  
  // ========== K-POP ==========
  'bts cake',
  'bangtan cake',
  'blackpink cake',
  'twice cake',
  'stray kids cake',
  'seventeen cake',
  'txt cake',
  'enhypen cake',
  'ateez cake',
  'nct cake',
  'exo cake',
  'newjeans cake',
  'aespa cake',
  'itzy cake',
  'red velvet cake design',
  'le sserafim cake',
  'jimin cake',
  'jungkook cake',
  'v cake',
  'rm cake',
  'jin cake',
  'suga cake',
  'jhope cake',
  'kpop cake',
  'kpop birthday cake',
  'lightstick cake',
  'finger heart cake',
  'ARMY cake',
  'BT21 cake',
  'borahae cake',
  'purple whale cake',
  'Blink cake',
  'black and pink cake',
  'SKZ cake',
  'SKZOO cake',
  'sajaboys cake',
  'ATINY cake',
  'Carat cake',
  'NewJeans bunny cake',
  'kpop demon hunter cake',
  'dark concept kpop cake',
  'fantasy kpop cake',
  'Dreamcatcher cake',
  'photocard cake',
  
  // ========== SPORTS ==========
  'football cake',
  'soccer cake',
  'basketball cake',
  'baseball cake',
  'nfl cake',
  'football team cake',
  'patriots cake',
  'cowboys cake',
  'chiefs cake',
  'lakers cake',
  'warriors cake',
  'bulls cake',
  'yankees cake',
  'dodgers cake',
  'red sox cake',
  'real madrid cake',
  'barcelona cake',
  'manchester united cake',
  'formula 1 cake',
  'f1 cake',
  'nascar cake',
  'ufc cake',
  'mma cake',
  'wrestling cake',
  'wwe cake',
  'cricket cake',
  'tennis cake',
  'golf cake',
  'hole in one cake',
  'hockey cake',
  'volleyball cake',
  'rugby cake',
  'boxing cake',
  'skateboard cake',
  'bmx cake',
  'surfing cake',
  'snowboard cake',
  
  // ========== TRAVEL & DESTINATIONS ==========
  'eiffel tower cake',
  'paris cake',
  'new york cake',
  'statue of liberty cake',
  'london cake',
  'big ben cake',
  'tokyo cake',
  'dubai cake',
  'burj khalifa cake',
  'las vegas cake',
  'hollywood cake',
  'beach cake',
  'tropical cake',
  'island cake',
  'mountain cake',
  'passport cake',
  'airplane cake',
  'plane cake',
  'luggage cake',
  'suitcase cake',
  'world map cake',
  'globe cake',
  'cruise ship cake',
  'hot air balloon cake',
  'travel cake',
  'adventure cake',
  
  // ========== BRANDS & LOGOS ==========
  'chanel cake',
  'gucci cake',
  'louis vuitton cake',
  'prada cake',
  'versace cake',
  'tiffany cake',
  'tiffany blue cake',
  'dior cake',
  'hermes cake',
  'starbucks cake',
  'mcdonalds cake',
  'coca cola cake',
  'pepsi cake',
  'dunkin cake',
  'krispy kreme cake',
  'in n out cake',
  'apple cake',
  'iphone cake',
  'nike cake',
  'adidas cake',
  'supreme cake',
  'tesla cake',
  'amazon cake',
  
  // ========== YOUTUBERS & INFLUENCERS ==========
  'mrbeast cake',
  'pewdiepie cake',
  'markiplier cake',
  'jacksepticeye cake',
  'dude perfect cake',
  'preston cake',
  'aphmau cake',
  'sssniperwolf cake',
  'dantdm cake',
  'ishowspeed cake',
  'ninja cake',
  'pokimane cake',
  'valkyrae cake',
  'dream cake',
  'technoblade cake',
  'tommyinnit cake',
  
  // ========== TV SHOWS & MOVIES ==========
  'wednesday cake',
  'wednesday addams cake',
  'stranger things cake',
  'the bear cake',
  'squid game cake',
  'bridgerton cake',
  'house of dragon cake',
  'the last of us cake',
  'succession cake',
  'yellowstone cake',
  'euphoria cake',
  'encanto cake',
  'moana cake',
  'turning red cake',
  'elemental cake',
  'wish cake',
  'inside out cake',
  'star wars cake',
  'harry potter cake',
  'hogwarts cake',
  'lord of the rings cake',
  'game of thrones cake',
  'marvel cake',
  'dc comics cake',
  'disney villain cake',
  'movie theme cake',
  'Barbie movie cake',
  'Golden Snitch cake',
  'Gryffindor cake',
  'Captain America shield cake',
  'Darth Vader cake',
  'Baby Yoda cake',
  'lightsaber cake',
  'Up movie cake',
  'Dune cake',
  'sandworm cake',
  'Netflix cake',
  'Hellfire Club cake',
  'Upside Down cake',
  'Eggo waffle cake',
  'Nevermore cake',
  'wisteria cake',
  'dalgona candy cake',
  'Money Heist cake',
  'La Casa de Papel cake',
  'The Queen\'s Gambit cake',
  'chessboard cake',
  'Disney cake',
  
  // ========== AGE-SPECIFIC ==========
  'baby cake',
  'kids cake',
  'toddler cake',
  'teenager cake',
  'adult birthday cake',
  '1st birthday cake',
  '18th birthday cake',
  '21st birthday cake',
  '30th birthday cake',
  '40th birthday cake',
  '50th birthday cake',
  
  // ========== ANIMALS ==========
  'cat cake',
  'dog cake',
  'puppy cake',
  'kitten cake',
  'bunny cake',
  'rabbit cake',
  'elephant cake',
  'lion cake',
  'tiger cake',
  'panda cake',
  'bear cake',
  'butterfly cake',
  'ladybug cake',
  
  // ========== STYLES & AESTHETICS ==========
  'simple cake',
  'elegant cake',
  'minimalist cake',
  'modern cake',
  'vintage cake',
  'rustic cake',
  'boho cake',
  'glamorous cake',
  'luxury cake',
  'cute cake',
  'funny cake',
  'unique cake',
  'creative cake',
  'aesthetic cake',
  'y2k cake',
  'cottagecore cake',
  'dark academia cake',
  'barbiecore cake',
  'coquette cake',
  'grunge cake',
  'indie cake',
  'retro cake',
  '80s cake',
  '90s cake',
  'neon cake',
  'holographic cake',
  'chrome cake',
  'cottagecore aesthetic cake',
  'fairycore cake',
  'goblincore cake',
  'dark feminine cake',
  'clean girl cake',
  'that girl cake',
  'korean minimalist cake',
  'doodle cake',
  'korean drawing cake',
  'vintage heart cake',
  'cherry on top cake',
  'korean style cake',
  
  // ========== COLORS & DECORATIONS ==========
  'pink cake',
  'blue cake',
  'purple cake',
  'gold cake',
  'rose gold cake',
  'rainbow cake',
  'pastel cake',
  'ombre cake',
  'drip cake',
  'floral cake',
  'rose cake',
  'flower cake',
  'heart cake',
  'star cake',
  'mirror glaze cake',
  'monochrome cake',
  'black and white cake',
  
  // ========== CURRENT TRENDS (2024-2025) ==========
  'money pulling cake',
  'pinata cake',
  'surprise inside cake',
  'explosion cake',
  'number cake',
  'letter cake',
  'geode cake',
  'marble cake design',
  'candle cake',
  'melting candle cake',
  'dome cake',
  'money cake',
  'pistachio cake',
  'bento cake',
  'lunchbox cake',
  'lambeth cake',
  
  // ========== HOBBIES & INTERESTS ==========
  'book cake',
  'book lover cake',
  'reading cake',
  'camera cake',
  'photography cake',
  'artist cake',
  'paint palette cake',
  'easel cake',
  'sewing cake',
  'sewing machine cake',
  'knitting cake',
  'yarn cake',
  'scrapbook cake',
  'writing cake',
  'typewriter cake',
  'gardening cake',
  'garden cake',
  'flower pot cake',
  'fishing cake',
  'camping cake',
  'tent cake',
  'hiking cake',
  'birdwatching cake',
  'chef cake',
  'cooking cake',
  'baking cake',
  'mixer cake',
  'wine cake',
  'sommelier cake',
  'coffee cake design',
  'foodie cake',
  'beach lover cake',
  'gym cake',
  'fitness cake',
  'weightlifting cake',
  'yoga cake',
  'meditation cake',
  'dance cake',
  'ballet cake',
  'art cake',
  
  // ========== PROFESSIONS ==========
  'doctor cake',
  'nurse cake',
  'teacher cake',
  'police cake',
  'firefighter cake',
  'construction cake',
  'engineer cake',
  'lawyer cake',
  'architect cake',
  'scientist cake',
  'pilot cake',
  'flight attendant cake',
  'photographer cake',
  'realtor cake',
  'dentist cake',
  'vet cake',
  'veterinarian cake',
  'pharmacist cake',
  'accountant cake',
  'mechanic cake',
  'hairdresser cake',
  'salon cake',
  
  // ========== FOOD THEMES ==========
  'fruit cake',
  'strawberry cake',
  'chocolate cake design',
  'vanilla cake design',
  'red velvet cake design',
  
  // ========== GENDER-SPECIFIC ==========
  'cake for boy',
  'cake for girl',
  'cake for men',
  'cake for women',
  'cake for boys',
  'cake for girls',
  
  // ========== INTERNET CULTURE ==========
  'meme cake',
  'tiktok cake',
  'instagram cake',
  'emoji cake',
  'viral cake',
  'trending cake',
  
  // ========== ZODIAC & SPIRITUAL ==========
  'zodiac cake',
  'astrology cake',
  'aries cake',
  'taurus cake',
  'gemini cake',
  'cancer cake',
  'leo cake',
  'virgo cake',
  'libra cake',
  'scorpio cake',
  'sagittarius cake',
  'capricorn cake',
  'aquarius cake',
  'pisces cake',
  'moon cake',
  'celestial cake',
  'crystal cake',
  'tarot cake',
  
  // ========== SEASONS & NATURE ==========
  'fall aesthetic cake',
  'autumn cake',
  'spring cake',
  'cherry blossom cake',
  'summer cake',
  'winter wonderland cake',
  'forest cake',
  'woodland cake',
  'ocean cake',
  'underwater cake',
  'space cake',
  'galaxy cake',
  'astronaut cake',
];

// ============================================================================
// CATEGORIZED KEYWORDS (For filtered search/suggestions)
// ============================================================================

export const KEYWORD_CATEGORIES = {
  occasions: [
    'birthday', 'wedding', 'anniversary', 'graduation', 
    'baby shower', 'bridal shower', 'retirement', 'engagement',
    'gender reveal', 'christening', 'baptism'
  ],
  
  characters: [
    'unicorn', 'dinosaur', 'princess', 'spiderman', 'batman',
    'frozen', 'elsa', 'paw patrol', 'minecraft', 'pokemon',
    'barbie', 'hello kitty', 'mickey mouse', 'peppa pig'
  ],
  
  anime: [
    'naruto', 'one piece', 'demon slayer', 'goku', 'dragon ball',
    'jujutsu kaisen', 'attack on titan', 'sailor moon', 'totoro'
  ],
  
  videogames: [
    'fortnite', 'minecraft', 'roblox', 'mario', 'sonic',
    'valorant', 'genshin impact', 'pokemon', 'zelda'
  ],
  
  kpop: [
    'bts', 'blackpink', 'twice', 'stray kids', 'seventeen',
    'txt', 'enhypen', 'newjeans', 'aespa', 'jimin', 'jungkook'
  ],
  
  celebrities: [
    'taylor swift', 'beyonce', 'ariana grande', 'billie eilish',
    'olivia rodrigo', 'bad bunny', 'drake'
  ],
  
  sports: [
    'football', 'soccer', 'basketball', 'baseball', 'tennis',
    'golf', 'hockey', 'cricket', 'f1', 'nfl', 'nba'
  ],
  
  brands: [
    'chanel', 'gucci', 'louis vuitton', 'starbucks', 'nike',
    'adidas', 'supreme', 'apple', 'tiffany'
  ],
  
  animals: [
    'cat', 'dog', 'bunny', 'elephant', 'lion', 'panda', 
    'butterfly', 'unicorn', 'dinosaur'
  ],
  
  styles: [
    'simple', 'elegant', 'minimalist', 'modern', 'vintage', 
    'rustic', 'glamorous', 'cute', 'aesthetic', 'y2k',
    'cottagecore', 'dark academia'
  ],
  
  colors: [
    'pink', 'blue', 'purple', 'gold', 'rainbow', 'pastel',
    'rose gold', 'black and white', 'monochrome'
  ],
  
  trends: [
    'bento', 'money pulling', 'drip', 'geode', 'number',
    'letter', 'mirror glaze', 'pinata', 'dome'
  ],
  
  hobbies: [
    'book', 'reading', 'photography', 'art', 'music',
    'gaming', 'travel', 'fitness', 'cooking', 'baking'
  ],
  
  travel: [
    'paris', 'new york', 'london', 'tokyo', 'dubai',
    'beach', 'tropical', 'airplane', 'passport'
  ],
  
  professions: [
    'doctor', 'nurse', 'teacher', 'lawyer', 'chef',
    'pilot', 'photographer', 'scientist', 'engineer'
  ]
};

// ============================================================================
// POPULAR COMBINATIONS (For smart suggestions)
// ============================================================================

export const POPULAR_COMBINATIONS = [
  'simple birthday cake',
  'elegant wedding cake',
  'cute baby shower cake',
  'unicorn birthday cake',
  'dinosaur birthday cake',
  'football birthday cake',
  'princess birthday cake',
  'pink unicorn cake',
  'blue dinosaur cake',
  'rainbow unicorn cake',
  'chocolate drip cake',
  'gold elegant cake',
  'pastel rainbow cake',
  'aesthetic birthday cake',
  'minimalist wedding cake',
  'vintage wedding cake',
  'boho wedding cake',
  'bts birthday cake',
  'blackpink birthday cake',
  'taylor swift birthday cake',
  'fortnite birthday cake',
  'minecraft birthday cake',
  'starbucks cake design',
  'tiktok birthday cake',
  'minimalist BTS cake',
  'vintage heart Barbie cake',
  'bento cake Totoro',
  'pastel Stray Kids cake',
  'lunchbox cake Harry Potter',
  'black and pink Wednesday cake',
  'doodle style BT21 cake',
];

// ============================================================================
// SEARCH HELPERS
// ============================================================================

/**
 * Get trending keywords (most popular/searched)
 */
export const TRENDING_KEYWORDS = [
  'bts cake',
  'taylor swift cake',
  'bento cake',
  'minimalist cake',
  'money pulling cake',
  'aesthetic cake',
  'blackpink cake',
  'fortnite cake',
  'minecraft cake',
  'unicorn cake',
  'dinosaur cake',
  'mrbeast cake',
  'wednesday cake',
  'stranger things cake',
  'demon slayer cake',
  'genshin impact cake',
];

/**
 * Quick search categories for UI
 */
export const QUICK_SEARCH_CATEGORIES = [
  { emoji: '🎂', label: 'Birthday', keywords: ['birthday cake', 'birthday'] },
  { emoji: '💒', label: 'Wedding', keywords: ['wedding cake', 'wedding'] },
  { emoji: '🦄', label: 'Unicorn', keywords: ['unicorn cake'] },
  { emoji: '🦕', label: 'Dinosaur', keywords: ['dinosaur cake'] },
  { emoji: '⚽', label: 'Sports', keywords: ['football', 'soccer', 'basketball'] },
  { emoji: '🎮', label: 'Gaming', keywords: ['fortnite', 'minecraft', 'roblox'] },
  { emoji: '🎵', label: 'K-Pop', keywords: ['bts', 'blackpink', 'kpop'] },
  { emoji: '✨', label: 'Aesthetic', keywords: ['aesthetic', 'cottagecore', 'y2k'] },
];