'use client';

import React from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';
import { Footer } from '@/components/Footer';

const Section: React.FC<{ title: string; children: React.ReactNode; className?: string }> = ({ title, children, className = '' }) => (
    <div className={`pt-6 border-t border-slate-200 ${className}`}>
        <h2 className="text-xl font-bold text-slate-800 mb-4">{title}</h2>
        <div className="space-y-4 text-slate-600 leading-relaxed">
            {children}
        </div>
    </div>
);

const TermsClient: React.FC = () => {
    const router = useRouter();

    return (
        <div className="min-h-screen bg-linear-to-br from-pink-50 via-purple-50 to-indigo-100 font-sans">
            <div className="max-w-4xl mx-auto px-4 py-8">
                {/* Header with Back Button */}
                <div className="mb-8">
                    <button
                        onClick={() => router.push('/')}
                        className="flex items-center gap-2 text-slate-600 hover:text-purple-600 transition-colors mb-4 group"
                    >
                        <div className="p-2 bg-white rounded-full shadow-sm group-hover:shadow-md transition-all">
                            <ArrowLeft size={20} />
                        </div>
                        <span className="font-medium">Back to Home</span>
                    </button>
                    <h1 className="text-3xl md:text-4xl font-bold bg-linear-to-r from-pink-500 via-purple-500 to-indigo-500 text-transparent bg-clip-text">
                        Terms of Service
                    </h1>
                </div>

                {/* Content Card */}
                <div className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl border border-slate-200 p-6 md:p-10 mb-12">
                    <p className="text-slate-600 mb-8 leading-relaxed">
                        Welcome to Genie.ph. By accessing or using our website and services, you agree to be bound by these Terms of Service.
                        Please read them carefully before using our platform.
                    </p>

                    <div className="space-y-8">
                        <Section title="1. Acceptance of Terms">
                            <p>
                                By creating an account, placing an order, or otherwise using Genie.ph, you agree to these Terms of Service
                                and our <a href="/privacy" className="text-purple-600 hover:underline">Privacy Policy</a>. If you do not agree,
                                please do not use our services.
                            </p>
                        </Section>

                        <Section title="2. About Our Services">
                            <p>
                                Genie.ph is an AI-powered online marketplace that connects customers with local bakeries and cake artisans
                                in Cebu, Philippines. We provide tools for cake design analysis, instant pricing, customization, and order facilitation.
                            </p>
                            <p>
                                Genie.ph acts as an intermediary platform. The cakes are prepared and delivered by independent baker partners.
                                We facilitate the transaction but are not directly responsible for the baking or delivery of products.
                            </p>
                        </Section>

                        <Section title="3. User Accounts">
                            <p>
                                You may need to create an account to access certain features. You are responsible for maintaining the
                                confidentiality of your account credentials and for all activities under your account.
                            </p>
                            <ul className="list-disc pl-5 space-y-2">
                                <li>You must provide accurate and complete information when creating an account.</li>
                                <li>You must be at least 18 years old, or have parental consent, to use our services.</li>
                                <li>You are responsible for keeping your password secure.</li>
                            </ul>
                        </Section>

                        <Section title="4. Orders & Payments">
                            <p>
                                When you place an order through Genie.ph, you are entering into a purchase agreement with the baker partner
                                fulfilling your order. Prices displayed are estimates generated by our AI system and confirmed by the baker.
                            </p>
                            <ul className="list-disc pl-5 space-y-2">
                                <li>All prices are listed in Philippine Pesos (PHP).</li>
                                <li>Payments are processed securely through Maya, GCash, or bank transfer.</li>
                                <li>Orders are confirmed once payment is received and accepted by the baker.</li>
                            </ul>
                        </Section>

                        <Section title="5. Cancellations & Refunds">
                            <p>
                                Custom cakes are perishable, made-to-order products. Please review our{' '}
                                <a href="/return-policy" className="text-purple-600 hover:underline">Return & Refund Policy</a> for
                                detailed information about cancellations and refunds.
                            </p>
                        </Section>

                        <Section title="6. Intellectual Property">
                            <p>
                                All content on Genie.ph, including text, graphics, logos, and software, is the property of Genie.ph or
                                its content suppliers and is protected by Philippine intellectual property laws. You may not reproduce,
                                distribute, or create derivative works without our written consent.
                            </p>
                            <p>
                                Cake designs uploaded by users remain the property of their respective owners. By uploading a design,
                                you grant Genie.ph a license to use the image for order processing, AI analysis, and platform improvement purposes.
                            </p>
                        </Section>

                        <Section title="7. User Conduct">
                            <p>You agree not to:</p>
                            <ul className="list-disc pl-5 space-y-2">
                                <li>Use the platform for any unlawful purpose.</li>
                                <li>Upload harmful, offensive, or infringing content.</li>
                                <li>Attempt to interfere with or disrupt the platform's operation.</li>
                                <li>Impersonate any person or entity.</li>
                            </ul>
                        </Section>

                        <Section title="8. Limitation of Liability">
                            <p>
                                Genie.ph provides the platform on an &quot;as is&quot; basis. We are not liable for any indirect, incidental,
                                or consequential damages arising from the use of our services. Our total liability shall not exceed the
                                amount you paid for the specific order in question.
                            </p>
                            <p>
                                As a marketplace, Genie.ph is not responsible for the quality of products made by independent baker partners,
                                though we maintain quality standards through our verification process.
                            </p>
                        </Section>

                        <Section title="9. Changes to Terms">
                            <p>
                                We reserve the right to update these Terms of Service at any time. Continued use of the platform after
                                changes constitutes acceptance of the updated terms. We will notify users of significant changes via
                                email or a notice on our website.
                            </p>
                        </Section>

                        <Section title="10. Contact Us">
                            <p>
                                If you have any questions about these Terms of Service, please contact us:
                            </p>
                            <ul className="list-disc pl-5 space-y-2">
                                <li>Email: <a href="mailto:support@genie.ph" className="text-purple-600 hover:underline">support@genie.ph</a></li>
                                <li>Phone: +63 908 940 8747</li>
                            </ul>
                        </Section>
                    </div>
                </div>
            </div>

            <Footer />
        </div>
    );
};

export default TermsClient;
