export const STICKY_ADD_TO_CART_BASE_OFFSET_PX = 72;
export const STICKY_ADD_TO_CART_AVAILABILITY_OVERLAP_PX = 12;
export const STICKY_ADD_TO_CART_AVAILABILITY_OFFSET_PX = 32 - STICKY_ADD_TO_CART_AVAILABILITY_OVERLAP_PX;
