export const STICKY_ADD_TO_CART_BASE_OFFSET_PX = 72;
export const STICKY_ADD_TO_CART_AVAILABILITY_EXTRA_HEIGHT_PX = 20;
export const STICKY_ADD_TO_CART_AVAILABILITY_OVERLAP_PX = 24;
export const STICKY_ADD_TO_CART_AVAILABILITY_TOTAL_HEIGHT_PX = 32 + STICKY_ADD_TO_CART_AVAILABILITY_EXTRA_HEIGHT_PX;
export const STICKY_ADD_TO_CART_AVAILABILITY_OFFSET_PX =
    STICKY_ADD_TO_CART_AVAILABILITY_TOTAL_HEIGHT_PX - STICKY_ADD_TO_CART_AVAILABILITY_OVERLAP_PX;
export const STICKY_ADD_TO_CART_AVAILABILITY_VERTICAL_PADDING_PX = 4 + (STICKY_ADD_TO_CART_AVAILABILITY_EXTRA_HEIGHT_PX / 2);

export const STICKY_ADD_TO_CART_PRINTOUT_OVERLAP_PX = 43;
export const STICKY_ADD_TO_CART_PRINTOUT_TOTAL_HEIGHT_PX = 52;
export const STICKY_ADD_TO_CART_PRINTOUT_OFFSET_PX =
    STICKY_ADD_TO_CART_PRINTOUT_TOTAL_HEIGHT_PX - STICKY_ADD_TO_CART_PRINTOUT_OVERLAP_PX;

