/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 490d7705962570c371ed6466b447daca)
interface __BaseEnv_Env {
	ACCESS_TEAM_DOMAIN: "";
	ACCESS_AUDIENCE: "";
	ACCESS_SERVICE_TOKEN_ID: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUDIENCE" | "ACCESS_SERVICE_TOKEN_ID">> {}
}
