/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5aef53be618a898352f7a76b4fbb0836)
interface __BaseEnv_Env {
	ACCESS_TEAM_DOMAIN: "https://withered-sunset-1d5b.cloudflareaccess.com";
	ACCESS_AUDIENCE: "0c00b9b51dea63e5a633a0fc62b2e3d091c2d9ab4006218a66e01cba770c109d";
	ACCESS_SERVICE_TOKEN_ID: "9fbc5d106e5d58c64f688e9b7ad31f35.access";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUDIENCE" | "ACCESS_SERVICE_TOKEN_ID">> {}
}
