-- Add dedicated Mother's Day and Father's Day holiday collections.
-- These complement the existing `dad-cake` (general dad theme) by being
-- specifically tied to the holiday keyword (`father's day`, `mother's day`).
-- Run scripts/update-collections-studio-images.ts after applying this
-- migration so sample_image, item_count, and publication_status are populated.
INSERT INTO public.cakegenie_collections (name, slug, tags, description)
VALUES
  (
    'Mother''s Day Cakes',
    'mothers-day-cakes',
    ARRAY[
      'Mother''s Day Cakes',
      'mother''s day',
      'mothers day',
      'mom birthday',
      'mama birthday',
      'mommy birthday',
      'floral mom',
      'mom floral',
      'floral mama',
      'mama floral',
      'floral mommy',
      'super mom',
      'mom bento',
      'mom minimalist',
      'mama minimalist',
      'mom sunflower',
      'sunflower mom',
      'sunflower mama',
      'mom chocolate',
      'mother and child',
      'mother''s day rose',
      'mother''s day pink',
      'mother''s day butterfly',
      'mother''s day heart',
      'mother''s day handbag',
      'mother''s day travel',
      'mom cake',
      'best mom',
      'nanay cake',
      'nanay birthday',
      'lola cake',
      'lola birthday',
      'mama cake',
      'lola floral',
      'nanay floral'
    ],
    'Find Mother''s Day cakes that match the woman you''re celebrating. Floral styles, minimalist designs, sunflower silhouettes, and warm-message cakes are all here, ready to customize with her name or a short note. Mama, lola, nanay, and best mom favorites are covered, with options to fit a quiet family lunch or a large reunion. Pick a starting point, change the colors and size, and review the quote. Delivery and pickup are available across Metro Cebu.'
  ),
  (
    'Father''s Day Cakes',
    'fathers-day-cakes',
    ARRAY[
      'Father''s Day Cakes',
      'father''s day',
      'fathers day',
      'dad birthday',
      'papa birthday',
      'super dad',
      'super daddy',
      'tuxedo dad',
      'tuxedo papa',
      'superman dad',
      'superman papa',
      'superhero dad',
      'superhero papa',
      'dad bento',
      'dad minimalist',
      'dad ribbon',
      'dad medal',
      'dad mustache',
      'mustache papa',
      'papa mustache',
      'dad chocolate',
      'best dad',
      'best papa',
      'dad husband',
      'husband dad',
      'father and child',
      'father''s day tie',
      'father''s day heart',
      'father''s day minimalist',
      'father''s day bento',
      'father''s day beer',
      'father''s day coffee',
      'father''s day golf',
      'father''s day fishing',
      'father''s day shirt',
      'father''s day superman',
      'father''s day chocolate',
      'father''s day handbag',
      'dad cake',
      'papa cake',
      'tatay cake',
      'tatay birthday',
      'lolo cake',
      'lolo birthday',
      'lolo floral',
      'tatay floral'
    ],
    'Find Father''s Day cakes for every kind of dad in your life. Tuxedo, superman, fishing, golf, and minimalist picks are all here, ready to customize with his name or a short message. Tatay, papa, lolo, and best dad favorites are covered, with options to fit a small family gathering or a big office party. Pick a starting point, change the colors and size, and review the quote. Delivery and pickup are available across Metro Cebu.'
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description;
