-- SQL Script to create and seed the cakegenie_collections table
CREATE TABLE public.cakegenie_collections (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    hits INTEGER DEFAULT 0,
    tags TEXT[] DEFAULT ARRAY[]::TEXT[],
    item_count INTEGER DEFAULT 0,
    sample_image TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster routing lookups by slug
CREATE INDEX idx_collections_slug ON public.cakegenie_collections (slug);

-- Create a helper function to set tags and slug if we were doing this dynamically,
-- but since we're seeding, we'll just insert the static data below.

INSERT INTO public.cakegenie_collections (name, slug, tags) VALUES
('80''S Cake', '80s-cake', ARRAY['80''S Cake']),
('Addams Family Cake', 'addams-family-cake', ARRAY['Addams Family Cake']),
('Adventure Time', 'adventure-time', ARRAY['Adventure Time']),
('Airplanes Cake', 'airplanes-cake', ARRAY['Airplanes Cake']),
('Alice Cake', 'alice-cake', ARRAY['Alice Cake']),
('Among us Cake', 'among-us-cake', ARRAY['Among us Cake']),
('Architect Cake', 'architect-cake', ARRAY['Architect Cake']),
('Art Cake', 'art-cake', ARRAY['Art Cake']),
('Attack on Titan Cake', 'attack-on-titan-cake', ARRAY['Attack on Titan Cake']),
('Aurora Cake', 'aurora-cake', ARRAY['Aurora Cake']),
('Avengers Cake', 'avengers-cake', ARRAY['Avengers Cake']),
('Axie Infinity Cake', 'axie-infinity-cake', ARRAY['Axie Infinity Cake']),
('Baby Cake', 'baby-cake', ARRAY['Baby Cake']),
('Baby Shark Cake', 'baby-shark-cake', ARRAY['Baby Shark Cake']),
('Bags & Shoes Cake', 'bags-and-shoes-cake', ARRAY['Bags & Shoes Cake', 'Bags Cake', 'Shoes Cake']),
('Ballerina Cake', 'ballerina-cake', ARRAY['Ballerina Cake']),
('Balloons Set', 'balloons-set', ARRAY['Balloons Set']),
('Bananas Pjs', 'bananas-pjs', ARRAY['Bananas Pjs']),
('Barbie Cake', 'barbie-cake', ARRAY['Barbie Cake']),
('Barney Cake', 'barney-cake', ARRAY['Barney Cake']),
('Baseball Cake', 'baseball-cake', ARRAY['Baseball Cake']),
('Basketball Cake', 'basketball-cake', ARRAY['Basketball Cake']),
('Batman Cake', 'batman-cake', ARRAY['Batman Cake']),
('Beach Cake', 'beach-cake', ARRAY['Beach Cake']),
('Bears Cake', 'bears-cake', ARRAY['Bears Cake']),
('Belle Cake', 'belle-cake', ARRAY['Belle Cake']),
('Ben10 Cake', 'ben10-cake', ARRAY['Ben10 Cake']),
('Bendy Cakes', 'bendy-cakes', ARRAY['Bendy Cakes']),
('Beyblade Cake', 'beyblade-cake', ARRAY['Beyblade Cake']),
('Bicycle Cake', 'bicycle-cake', ARRAY['Bicycle Cake']),
('Big Hero Cake', 'big-hero-cake', ARRAY['Big Hero Cake']),
('Birds Cake', 'birds-cake', ARRAY['Birds Cake']),
('Birthday Backdrop', 'birthday-backdrop', ARRAY['Birthday Backdrop']),
('BL Cake', 'bl-cake', ARRAY['BL Cake']),
('Blackpink Cake', 'blackpink-cake', ARRAY['Blackpink Cake']),
('Blippi Cake', 'blippi-cake', ARRAY['Blippi Cake']),
('Blue Birthday Cake', 'blue-birthday-cake', ARRAY['Blue Birthday Cake']),
('Blues Clues', 'blues-clues', ARRAY['Blues Clues']),
('Blues Clues Cake', 'blues-clues-cake', ARRAY['Blues Clues Cake']),
('Bluey Cake', 'bluey-cake', ARRAY['Bluey Cake']),
('Books Cake', 'books-cake', ARRAY['Books Cake']),
('Boss Baby Cake', 'boss-baby-cake', ARRAY['Boss Baby Cake']),
('Boxing Cake', 'boxing-cake', ARRAY['Boxing Cake']),
('Bride Cake', 'bride-cake', ARRAY['Bride Cake']),
('BTS Cake', 'bts-cake', ARRAY['BTS Cake']),
('Bugs Cake', 'bugs-cake', ARRAY['Bugs Cake']),
('Bunny Cake', 'bunny-cake', ARRAY['Bunny Cake']),
('Bus Train Trucks Cake', 'bus-train-trucks-cake', ARRAY['Bus Train Trucks Cake']),
('Butterflies Cake', 'butterflies-cake', ARRAY['Butterflies Cake']),
('Camping Cake', 'camping-cake', ARRAY['Camping Cake']),
('Candyland Cake', 'candyland-cake', ARRAY['Candyland Cake']),
('Cards Cake', 'cards-cake', ARRAY['Cards Cake']),
('Care Bears Cake', 'care-bears-cake', ARRAY['Care Bears Cake']),
('Carnival Cake', 'carnival-cake', ARRAY['Carnival Cake']),
('Cars (Pixar) Cake', 'cars-pixar-cake', ARRAY['Cars (Pixar) Cake']),
('Cartoon', 'cartoon', ARRAY['Cartoon']),
('Cartoon Cake', 'cartoon-cake', ARRAY['Cartoon Cake']),
('Cat Cake', 'cat-cake', ARRAY['Cat Cake']),
('Chainsaw Man Cake', 'chainsaw-man-cake', ARRAY['Chainsaw Man Cake']),
('Chef Cake', 'chef-cake', ARRAY['Chef Cake']),
('Cherry Blossom Cake', 'cherry-blossom-cake', ARRAY['Cherry Blossom Cake']),
('Chess Cake', 'chess-cake', ARRAY['Chess Cake']),
('Chocolate Factory Cake', 'chocolate-factory-cake', ARRAY['Chocolate Factory Cake']),
('Christening Angel Cake', 'christening-angel-cake', ARRAY['Christening Angel Cake']),
('Christening Boy Cake', 'christening-boy-cake', ARRAY['Christening Boy Cake']),
('Christening Girl Cake', 'christening-girl-cake', ARRAY['Christening Girl Cake']),
('Christening Star Cake', 'christening-star-cake', ARRAY['Christening Star Cake']),
('Christmas Cake', 'christmas-cake', ARRAY['Christmas Cake']),
('Chuchu TV', 'chuchu-tv', ARRAY['Chuchu TV']),
('Cinderella Cake', 'cinderella-cake', ARRAY['Cinderella Cake']),
('Cocomelon Cake', 'cocomelon-cake', ARRAY['Cocomelon Cake']),
('Coffee Cake', 'coffee-cake', ARRAY['Coffee Cake']),
('Comics Cake', 'comics-cake', ARRAY['Comics Cake']),
('Construction Cake', 'construction-cake', ARRAY['Construction Cake']),
('Crown Cake', 'crown-cake', ARRAY['Crown Cake']),
('Cryptocurrency Cake', 'cryptocurrency-cake', ARRAY['Cryptocurrency Cake']),
('Dad Cake', 'dad-cake', ARRAY['Dad Cake']),
('Dancer Cake', 'dancer-cake', ARRAY['Dancer Cake']),
('Dave and Ava Cake', 'dave-and-ava-cake', ARRAY['Dave and Ava Cake']),
('Day of the Dead', 'day-of-the-dead', ARRAY['Day of the Dead']),
('Debut Cake', 'debut-cake', ARRAY['Debut Cake']),
('Dedication Cake', 'dedication-cake', ARRAY['Dedication Cake']),
('Demon Slayer Cake', 'demon-slayer-cake', ARRAY['Demon Slayer Cake']),
('Denim Cake', 'denim-cake', ARRAY['Denim Cake']),
('Diana and Roma Cake', 'diana-and-roma-cake', ARRAY['Diana and Roma Cake']),
('Dinosaurs Cake', 'dinosaurs-cake', ARRAY['Dinosaurs Cake']),
('Doc Mcstuffins', 'doc-mcstuffins', ARRAY['Doc Mcstuffins']),
('Doctor Cake', 'doctor-cake', ARRAY['Doctor Cake']),
('Dog Cake', 'dog-cake', ARRAY['Dog Cake']),
('Donuts Macarons Cake', 'donuts-macarons-cake', ARRAY['Donuts Macarons Cake']),
('Doodle Cake', 'doodle-cake', ARRAY['Doodle Cake']),
('Dora the Explorer Cake', 'dora-the-explorer-cake', ARRAY['Dora the Explorer Cake']),
('Doraemon Cake', 'doraemon-cake', ARRAY['Doraemon Cake']),
('Dragon Ball Z Cake', 'dragon-ball-z-cake', ARRAY['Dragon Ball Z Cake']),
('Dream Catcher Cake', 'dream-catcher-cake', ARRAY['Dream Catcher Cake']),
('Drinks Cake', 'drinks-cake', ARRAY['Drinks Cake']),
('Drip Cake', 'drip-cake', ARRAY['Drip Cake']),
('Easter Cake', 'easter-cake', ARRAY['Easter Cake']),
('Edible Photo (Cake Wrap)', 'edible-photo-cake-wrap', ARRAY['Edible Photo (Cake Wrap)']),
('Edible Photo Axie Cake', 'edible-photo-axie-cake', ARRAY['Edible Photo Axie Cake']),
('Edible Photo BBM Cake', 'edible-photo-bbm-cake', ARRAY['Edible Photo BBM Cake']),
('Edible Photo Birthday Cake', 'edible-photo-birthday-cake', ARRAY['Edible Photo Birthday Cake']),
('Edible Photo Cocomelon Cake', 'edible-photo-cocomelon-cake', ARRAY['Edible Photo Cocomelon Cake']),
('Edible Photo Congrats Cake', 'edible-photo-congrats-cake', ARRAY['Edible Photo Congrats Cake']),
('Edible Photo Flowers', 'edible-photo-flowers', ARRAY['Edible Photo Flowers']),
('Edible photo Instagram cake', 'edible-photo-instagram-cake', ARRAY['Edible photo Instagram cake']),
('Edible Photo NBA', 'edible-photo-nba', ARRAY['Edible Photo NBA']),
('Edible Photo Start-up KDrama Cake', 'edible-photo-start-up-kdrama-cake', ARRAY['Edible Photo Start-up KDrama Cake']),
('Edible Photo Stranger Things Cake', 'edible-photo-stranger-things-cake', ARRAY['Edible Photo Stranger Things Cake']),
('Encanto Cake', 'encanto-cake', ARRAY['Encanto Cake']),
('Engineer Cake', 'engineer-cake', ARRAY['Engineer Cake']),
('Fairy Cake', 'fairy-cake', ARRAY['Fairy Cake']),
('Farm Animals Cake', 'farm-animals-cake', ARRAY['Farm Animals Cake']),
('Ferrari Cake', 'ferrari-cake', ARRAY['Ferrari Cake']),
('Fifty Cake', 'fifty-cake', ARRAY['Fifty Cake']),
('Fire Fighter Cake', 'fire-fighter-cake', ARRAY['Fire Fighter Cake']),
('Fishing Cake', 'fishing-cake', ARRAY['Fishing Cake']),
('Flamingo Cake', 'flamingo-cake', ARRAY['Flamingo Cake']),
('Floral Cake', 'floral-cake', ARRAY['Floral Cake']),
('Fortnite Cake', 'fortnite-cake', ARRAY['Fortnite Cake']),
('Friends Cake', 'friends-cake', ARRAY['Friends Cake']),
('Frisbee Cake', 'frisbee-cake', ARRAY['Frisbee Cake']),
('Frog Cake', 'frog-cake', ARRAY['Frog Cake']),
('Frozen Cake', 'frozen-cake', ARRAY['Frozen Cake']),
('Fruits & Veggies Cake', 'fruits-and-veggies-cake', ARRAY['Fruits & Veggies Cake']),
('Gabby''s Dollhouse', 'gabbys-dollhouse', ARRAY['Gabby''s Dollhouse']),
('Gacha Life Cake', 'gacha-life-cake', ARRAY['Gacha Life Cake']),
('Garden Cake', 'garden-cake', ARRAY['Garden Cake']),
('Gender Reveal Cake', 'gender-reveal-cake', ARRAY['Gender Reveal Cake']),
('Genshin Impact Cake', 'genshin-impact-cake', ARRAY['Genshin Impact Cake']),
('Godzilla Cake', 'godzilla-cake', ARRAY['Godzilla Cake']),
('Golf Cake', 'golf-cake', ARRAY['Golf Cake']),
('Graduation Cake', 'graduation-cake', ARRAY['Graduation Cake']),
('Graffiti Cake', 'graffiti-cake', ARRAY['Graffiti Cake']),
('Gravity Falls Cake', 'gravity-falls-cake', ARRAY['Gravity Falls Cake']),
('Gummy Bear Cake', 'gummy-bear-cake', ARRAY['Gummy Bear Cake']),
('Gundam Cake', 'gundam-cake', ARRAY['Gundam Cake']),
('Halloween Cake', 'halloween-cake', ARRAY['Halloween Cake']),
('Harry Potter Cake', 'harry-potter-cake', ARRAY['Harry Potter Cake']),
('Healthcare Cake', 'healthcare-cake', ARRAY['Healthcare Cake']),
('Hello Kitty Cake', 'hello-kitty-cake', ARRAY['Hello Kitty Cake']),
('Horse Cake', 'horse-cake', ARRAY['Horse Cake']),
('Hot air balloon Cake', 'hot-air-balloon-cake', ARRAY['Hot air balloon Cake']),
('Hotwheels Cake', 'hotwheels-cake', ARRAY['Hotwheels Cake']),
('House Warming Cake', 'house-warming-cake', ARRAY['House Warming Cake']),
('Iglesia Ni Cristo Cake', 'iglesia-ni-cristo-cake', ARRAY['Iglesia Ni Cristo Cake']),
('Jasmine Cake', 'jasmine-cake', ARRAY['Jasmine Cake']),
('Jolibee Cake', 'jolibee-cake', ARRAY['Jolibee Cake']),
('Jujutsu Kaisen Cake', 'jujutsu-kaisen-cake', ARRAY['Jujutsu Kaisen Cake']),
('Justice League Cake', 'justice-league-cake', ARRAY['Justice League Cake']),
('KDrama Cake', 'kdrama-cake', ARRAY['KDrama Cake']),
('Kids Cakes', 'kids-cakes', ARRAY['Kids Cakes']),
('Kongsuni Cake', 'kongsuni-cake', ARRAY['Kongsuni Cake']),
('Kpop Cake', 'kpop-cake', ARRAY['Kpop Cake']),
('Lady Bug Cake', 'lady-bug-cake', ARRAY['Lady Bug Cake']),
('Lanky Box Cake', 'lanky-box-cake', ARRAY['Lanky Box Cake']),
('Lechon Cake', 'lechon-cake', ARRAY['Lechon Cake']),
('Lego Cake', 'lego-cake', ARRAY['Lego Cake']),
('Letters Num Cake', 'letters-num-cake', ARRAY['Letters Num Cake']),
('Lilo Stitch Cake', 'lilo-stitch-cake', ARRAY['Lilo Stitch Cake']),
('Little Man Cake', 'little-man-cake', ARRAY['Little Man Cake']),
('Little Pony Cake', 'little-pony-cake', ARRAY['Little Pony Cake']),
('Little Twins Cake', 'little-twins-cake', ARRAY['Little Twins Cake']),
('Llama Cake', 'llama-cake', ARRAY['Llama Cake']),
('LOL Surprise Cake', 'lol-surprise-cake', ARRAY['LOL Surprise Cake']),
('Looney Toons', 'looney-toons', ARRAY['Looney Toons']),
('Lotto Cake', 'lotto-cake', ARRAY['Lotto Cake']),
('Love Cake', 'love-cake', ARRAY['Love Cake']),
('Mahjong Cake', 'mahjong-cake', ARRAY['Mahjong Cake']),
('Make up Cake', 'make-up-cake', ARRAY['Make up Cake']),
('Maleficent Cake', 'maleficent-cake', ARRAY['Maleficent Cake']),
('Mcdo Cake', 'mcdo-cake', ARRAY['Mcdo Cake']),
('Merida Cake', 'merida-cake', ARRAY['Merida Cake']),
('Mermaid Cake', 'mermaid-cake', ARRAY['Mermaid Cake']),
('Mickey Mouse Cake', 'mickey-mouse-cake', ARRAY['Mickey Mouse Cake']),
('Military Cake', 'military-cake', ARRAY['Military Cake']),
('Milktea Cake', 'milktea-cake', ARRAY['Milktea Cake']),
('Minecraft Cake', 'minecraft-cake', ARRAY['Minecraft Cake']),
('Minimalist Cake', 'minimalist-cake', ARRAY['Minimalist Cake']),
('Minions Cake', 'minions-cake', ARRAY['Minions Cake']),
('Minnie Mouse Cake', 'minnie-mouse-cake', ARRAY['Minnie Mouse Cake']),
('Moana Cake', 'moana-cake', ARRAY['Moana Cake']),
('Mobile Legends Cake', 'mobile-legends-cake', ARRAY['Mobile Legends Cake']),
('Money Cake', 'money-cake', ARRAY['Money Cake']),
('Money Heist Cake', 'money-heist-cake', ARRAY['Money Heist Cake']),
('Monster Cake', 'monster-cake', ARRAY['Monster Cake']),
('Monsters Cake', 'monsters-cake', ARRAY['Monsters Cake']),
('Motorcycle Cake', 'motorcycle-cake', ARRAY['Motorcycle Cake']),
('Movie Cake', 'movie-cake', ARRAY['Movie Cake']),
('Music Cake', 'music-cake', ARRAY['Music Cake']),
('My Little Pony Cake', 'my-little-pony-cake', ARRAY['My Little Pony Cake']),
('Naked Cake', 'naked-cake', ARRAY['Naked Cake']),
('Naruto Cake', 'naruto-cake', ARRAY['Naruto Cake']),
('Naughty Cake', 'naughty-cake', ARRAY['Naughty Cake']),
('Nautical Cake', 'nautical-cake', ARRAY['Nautical Cake']),
('Nerf Cake', 'nerf-cake', ARRAY['Nerf Cake']),
('Netflix Cake', 'netflix-cake', ARRAY['Netflix Cake']),
('New Year Cake', 'new-year-cake', ARRAY['New Year Cake']),
('Ninja Cake', 'ninja-cake', ARRAY['Ninja Cake']),
('Number Blocks', 'number-blocks', ARRAY['Number Blocks']),
('Number Blocks Cake', 'number-blocks-cake', ARRAY['Number Blocks Cake']),
('Nurse Cake', 'nurse-cake', ARRAY['Nurse Cake']),
('One Piece Cake', 'one-piece-cake', ARRAY['One Piece Cake']),
('One Punch Man Cake', 'one-punch-man-cake', ARRAY['One Punch Man Cake']),
('Others Cake', 'others-cake', ARRAY['Others Cake']),
('Panda Cake', 'panda-cake', ARRAY['Panda Cake']),
('Paw Patrol Cake', 'paw-patrol-cake', ARRAY['Paw Patrol Cake']),
('Peppa Pig Cake', 'peppa-pig-cake', ARRAY['Peppa Pig Cake']),
('Peterpan Cake', 'peterpan-cake', ARRAY['Peterpan Cake']),
('Pirate Cake', 'pirate-cake', ARRAY['Pirate Cake']),
('Pizza Cake', 'pizza-cake', ARRAY['Pizza Cake']),
('PJ Mask Cake', 'pj-mask-cake', ARRAY['PJ Mask Cake']),
('Pocoyo Cake', 'pocoyo-cake', ARRAY['Pocoyo Cake']),
('Pokemon Cake', 'pokemon-cake', ARRAY['Pokemon Cake']),
('Police Cake', 'police-cake', ARRAY['Police Cake']),
('Pooh Cake', 'pooh-cake', ARRAY['Pooh Cake']),
('Pool Cake', 'pool-cake', ARRAY['Pool Cake']),
('Pop-it Cake', 'pop-it-cake', ARRAY['Pop-it Cake']),
('Poppy Playtime Cake', 'poppy-playtime-cake', ARRAY['Poppy Playtime Cake']),
('Pororo Cake', 'pororo-cake', ARRAY['Pororo Cake']),
('Power Puff Girls', 'power-puff-girls', ARRAY['Power Puff Girls']),
('Power Rangers Cake', 'power-rangers-cake', ARRAY['Power Rangers Cake']),
('President Nadine Cake', 'president-nadine-cake', ARRAY['President Nadine Cake']),
('Princess Cake', 'princess-cake', ARRAY['Princess Cake']),
('PVZ Cake', 'pvz-cake', ARRAY['PVZ Cake']),
('Quarantine Cake', 'quarantine-cake', ARRAY['Quarantine Cake']),
('Rainbow (Boho) Cake', 'rainbow-boho-cake', ARRAY['Rainbow (Boho) Cake']),
('Rainbow Cake', 'rainbow-cake', ARRAY['Rainbow Cake']),
('Rainbow Friends Cake', 'rainbow-friends-cake', ARRAY['Rainbow Friends Cake']),
('Raindeer Cake', 'raindeer-cake', ARRAY['Raindeer Cake']),
('Rapunzel Cake', 'rapunzel-cake', ARRAY['Rapunzel Cake']),
('Raya Cakes', 'raya-cakes', ARRAY['Raya Cakes']),
('Red Birthday Cake', 'red-birthday-cake', ARRAY['Red Birthday Cake']),
('Ribbon Cake', 'ribbon-cake', ARRAY['Ribbon Cake']),
('Roblox Cake', 'roblox-cake', ARRAY['Roblox Cake']),
('Robocar Poli Cake', 'robocar-poli-cake', ARRAY['Robocar Poli Cake']),
('Robots Cake', 'robots-cake', ARRAY['Robots Cake']),
('Rooster Cake', 'rooster-cake', ARRAY['Rooster Cake']),
('Rosettes Cake', 'rosettes-cake', ARRAY['Rosettes Cake']),
('Safari Cake', 'safari-cake', ARRAY['Safari Cake']),
('Science Cake', 'science-cake', ARRAY['Science Cake']),
('Senior Citizen Card Cake', 'senior-citizen-card-cake', ARRAY['Senior Citizen Card Cake']),
('Sesame St Cake', 'sesame-st-cake', ARRAY['Sesame St Cake']),
('Sew Cake', 'sew-cake', ARRAY['Sew Cake']),
('Shimmer and Shine Cake', 'shimmer-and-shine-cake', ARRAY['Shimmer and Shine Cake']),
('Shirt Cake', 'shirt-cake', ARRAY['Shirt Cake']),
('Shopee Lazada Cake', 'shopee-lazada-cake', ARRAY['Shopee Lazada Cake']),
('Shopkins Cake', 'shopkins-cake', ARRAY['Shopkins Cake']),
('Sinulog Cake', 'sinulog-cake', ARRAY['Sinulog Cake']),
('Siren Head', 'siren-head', ARRAY['Siren Head']),
('Skater Cake', 'skater-cake', ARRAY['Skater Cake']),
('Sky Diving Cake', 'sky-diving-cake', ARRAY['Sky Diving Cake']),
('Smurfs Cake', 'smurfs-cake', ARRAY['Smurfs Cake']),
('Snow White Cake', 'snow-white-cake', ARRAY['Snow White Cake']),
('Soccer Cake', 'soccer-cake', ARRAY['Soccer Cake']),
('Soccer Fondant Cake', 'soccer-fondant-cake', ARRAY['Soccer Fondant Cake']),
('Social Media Cake', 'social-media-cake', ARRAY['Social Media Cake']),
('Sofia Cake', 'sofia-cake', ARRAY['Sofia Cake']),
('Sonic Cake', 'sonic-cake', ARRAY['Sonic Cake']),
('Space Cake', 'space-cake', ARRAY['Space Cake']),
('Space Jam Cake', 'space-jam-cake', ARRAY['Space Jam Cake']),
('Sparkling Fountain Candle', 'sparkling-fountain-candle', ARRAY['Sparkling Fountain Candle']),
('Spiderman Cake', 'spiderman-cake', ARRAY['Spiderman Cake']),
('Spongebob Cake', 'spongebob-cake', ARRAY['Spongebob Cake']),
('Sports Cake', 'sports-cake', ARRAY['Sports Cake']),
('Spy x Family Cake', 'spy-x-family-cake', ARRAY['Spy x Family Cake']),
('SquidGame Cake', 'squidgame-cake', ARRAY['SquidGame Cake']),
('Starry Night Cake', 'starry-night-cake', ARRAY['Starry Night Cake']),
('Stars Cake', 'stars-cake', ARRAY['Stars Cake']),
('Starwars Cake', 'starwars-cake', ARRAY['Starwars Cake']),
('Stranger Things Cake', 'stranger-things-cake', ARRAY['Stranger Things Cake']),
('Strawberry Shortcake Cake', 'strawberry-shortcake-cake', ARRAY['Strawberry Shortcake Cake']),
('Suit Cake', 'suit-cake', ARRAY['Suit Cake']),
('Summer Cake', 'summer-cake', ARRAY['Summer Cake']),
('Sunflower Cake', 'sunflower-cake', ARRAY['Sunflower Cake']),
('Super Jojo Cake', 'super-jojo-cake', ARRAY['Super Jojo Cake']),
('Super Mario Cake', 'super-mario-cake', ARRAY['Super Mario Cake']),
('Superman Cake', 'superman-cake', ARRAY['Superman Cake']),
('Teen Titans Cake', 'teen-titans-cake', ARRAY['Teen Titans Cake']),
('Tennis Cake', 'tennis-cake', ARRAY['Tennis Cake']),
('The Flash Cake', 'the-flash-cake', ARRAY['The Flash Cake']),
('Tiktok Cake', 'tiktok-cake', ARRAY['Tiktok Cake']),
('Tinder Cake', 'tinder-cake', ARRAY['Tinder Cake']),
('Toca Life Cake', 'toca-life-cake', ARRAY['Toca Life Cake']),
('Top Wing Cake', 'top-wing-cake', ARRAY['Top Wing Cake']),
('Toy Story Cake', 'toy-story-cake', ARRAY['Toy Story Cake']),
('Transformers Cake', 'transformers-cake', ARRAY['Transformers Cake']),
('Travel Cake', 'travel-cake', ARRAY['Travel Cake']),
('Trolls Cake', 'trolls-cake', ARRAY['Trolls Cake']),
('Tropical Cake', 'tropical-cake', ARRAY['Tropical Cake']),
('Turning Red Cake', 'turning-red-cake', ARRAY['Turning Red Cake']),
('Turtles Cake', 'turtles-cake', ARRAY['Turtles Cake']),
('Under the Sea Cake', 'under-the-sea-cake', ARRAY['Under the Sea Cake']),
('Unicorn Cake', 'unicorn-cake', ARRAY['Unicorn Cake']),
('Uniform Cake', 'uniform-cake', ARRAY['Uniform Cake']),
('United Nations Cake', 'united-nations-cake', ARRAY['United Nations Cake']),
('Upin & Ipin Cake', 'upin-ipin-cake', ARRAY['Upin & Ipin Cake']),
('Valentines Cake', 'valentines-cake', ARRAY['Valentines Cake']),
('Valentines Cake and Cupcakes Set', 'valentines-cake-and-cupcakes-set', ARRAY['Valentines Cake and Cupcakes Set']),
('Video Games Cake', 'video-games-cake', ARRAY['Video Games Cake']),
('Vintage Cake', 'vintage-cake', ARRAY['Vintage Cake']),
('Volleyball Cake', 'volleyball-cake', ARRAY['Volleyball Cake']),
('Voltes V Cake', 'voltes-v-cake', ARRAY['Voltes V Cake']),
('Walfoo Cake', 'walfoo-cake', ARRAY['Walfoo Cake']),
('Watch Cake', 'watch-cake', ARRAY['Watch Cake']),
('Wedding (Silver) Cake', 'wedding-silver-cake', ARRAY['Wedding (Silver) Cake']),
('Wedding Cake', 'wedding-cake', ARRAY['Wedding Cake']),
('Wednesday Cake', 'wednesday-cake', ARRAY['Wednesday Cake']),
('Wheels Cake', 'wheels-cake', ARRAY['Wheels Cake']),
('Women Cake', 'women-cake', ARRAY['Women Cake']),
('Wonder Woman Cake', 'wonder-woman-cake', ARRAY['Wonder Woman Cake']),
('Word Party Cake', 'word-party-cake', ARRAY['Word Party Cake']),
('Yoyo Cake', 'yoyo-cake', ARRAY['Yoyo Cake']),
('X-Men Cake', 'x-men-cake', ARRAY['X-Men Cake']),
('Golden Ball Cake', 'golden-ball-cake', ARRAY['Golden Ball Cake']),
('Katuri Cake', 'katuri-cake', ARRAY['Katuri Cake']),
('Anime Cake', 'anime-cake', ARRAY['Anime Cake']),
('Meekah Cake', 'meekah-cake', ARRAY['Meekah Cake']),
('Totoro Cake', 'totoro-cake', ARRAY['Totoro Cake']),
('Kuromi Cake', 'kuromi-cake', ARRAY['Kuromi Cake']),
('Skibidi Cake', 'skibidi-cake', ARRAY['Skibidi Cake']),
('Cinnamoroll Cake', 'cinnamoroll-cake', ARRAY['Cinnamoroll Cake']),
('Inside Out Cake', 'inside-out-cake', ARRAY['Inside Out Cake']),
('Ms Rachel Cake', 'ms-rachel-cake', ARRAY['Ms Rachel Cake']),
('Lucas the Spider Cake', 'lucas-the-spider-cake', ARRAY['Lucas the Spider Cake']),
('Bini Cake', 'bini-cake', ARRAY['Bini Cake']),
('Groovy Cake', 'groovy-cake', ARRAY['Groovy Cake']),
('My Melody Cake', 'my-melody-cake', ARRAY['My Melody Cake']),
('Rubiks Cube Cake', 'rubiks-cube-cake', ARRAY['Rubiks Cube Cake']),
('Zumba Cake', 'zumba-cake', ARRAY['Zumba Cake']),
('Boss Cake', 'boss-cake', ARRAY['Boss Cake']),
('Beshy Cake', 'beshy-cake', ARRAY['Beshy Cake']),
('Going Seventeen Cake', 'going-seventeen-cake', ARRAY['Going Seventeen Cake']),
('Billiards Cake', 'billiards-cake', ARRAY['Billiards Cake']),
('Hulk Cake', 'hulk-cake', ARRAY['Hulk Cake']),
('Casino Cake', 'casino-cake', ARRAY['Casino Cake']),
('Little Prince Cake', 'little-prince-cake', ARRAY['Little Prince Cake']),
('Flying Kites Cake', 'flying-kites-cake', ARRAY['Flying Kites Cake']),
('Darts Cake', 'darts-cake', ARRAY['Darts Cake']),
('Efficascent Oil Cake', 'efficascent-oil-cake', ARRAY['Efficascent Oil Cake']),
('Senior Cake', 'senior-cake', ARRAY['Senior Cake']),
('One Cake', 'one-cake', ARRAY['One Cake']),
('Avatar Cake', 'avatar-cake', ARRAY['Avatar Cake']),
('Mulan Cake', 'mulan-cake', ARRAY['Mulan Cake']),
('Sing Cake', 'sing-cake', ARRAY['Sing Cake']),
('Crossword Puzzle Cake', 'crossword-puzzle-cake', ARRAY['Crossword Puzzle Cake']),
('Karate Cake', 'karate-cake', ARRAY['Karate Cake']),
('Darna Cake', 'darna-cake', ARRAY['Darna Cake']),
('Farewell Cake', 'farewell-cake', ARRAY['Farewell Cake']),
('Balloon Cake', 'balloon-cake', ARRAY['Balloon Cake']),
('Pompompurin Cake', 'pompompurin-cake', ARRAY['Pompompurin Cake']),
('Rock and Roll Cake', 'rock-and-roll-cake', ARRAY['Rock and Roll Cake']),
('Louis Vuitton Cake', 'louis-vuitton-cake', ARRAY['Louis Vuitton Cake']),
('Keroppi Cake', 'keroppi-cake', ARRAY['Keroppi Cake']),
('Teachers Day Cake', 'teachers-day-cake', ARRAY['Teachers Day Cake']),
('Edible Photo Anniversary Cake', 'edible-photo-anniversary-cake', ARRAY['Edible Photo Anniversary Cake']),
('Sailor Moon Cake', 'sailor-moon-cake', ARRAY['Sailor Moon Cake']),
('Disco Cake', 'disco-cake', ARRAY['Disco Cake']),
('Jeans Cake', 'jeans-cake', ARRAY['Jeans Cake']),
('Sushi Cake', 'sushi-cake', ARRAY['Sushi Cake']),
('Spider Cake', 'spider-cake', ARRAY['Spider Cake']),
('Deadpool Cake', 'deadpool-cake', ARRAY['Deadpool Cake']),
('Taylor Swift Cake', 'taylor-swift-cake', ARRAY['Taylor Swift Cake']),
('Playdoh Cake', 'playdoh-cake', ARRAY['Playdoh Cake']),
('Bebefinn Cake', 'bebefinn-cake', ARRAY['Bebefinn Cake']),
('Twenty Cake', 'twenty-cake', ARRAY['Twenty Cake']),
('Rotary Club Cake', 'rotary-club-cake', ARRAY['Rotary Club Cake']),
('Listener Kids Cake', 'listener-kids-cake', ARRAY['Listener Kids Cake']),
('Super Simple Songs Cake', 'super-simple-songs-cake', ARRAY['Super Simple Songs Cake']),
('Koala Cake', 'koala-cake', ARRAY['Koala Cake']),
('Scary Pumpkin Witch Cake', 'scary-pumpkin-witch-cake', ARRAY['Scary Pumpkin Witch Cake']),
('Happy Halloween Cake', 'happy-halloween-cake', ARRAY['Happy Halloween Cake']),
('Labubu Cake', 'labubu-cake', ARRAY['Labubu Cake']),
('Olivia Rodrigo Cake', 'olivia-rodrigo-cake', ARRAY['Olivia Rodrigo Cake']),
('Foodpanda Cake', 'foodpanda-cake', ARRAY['Foodpanda Cake']),
('Digital Circus Cake', 'digital-circus-cake', ARRAY['Digital Circus Cake']),
('Smiling Critters Cake', 'smiling-critters-cake', ARRAY['Smiling Critters Cake']),
('Tobot Cake', 'tobot-cake', ARRAY['Tobot Cake']),
('Oko Lele cake', 'oko-lele-cake', ARRAY['Oko Lele cake']),
('Congratulations Cake', 'congratulations-cake', ARRAY['Congratulations Cake']),
('Bingo Cake', 'bingo-cake', ARRAY['Bingo Cake']),
('Fast and Furious Cake', 'fast-and-furious-cake', ARRAY['Fast and Furious Cake']),
('Noah''s Ark Cake', 'noahs-ark-cake', ARRAY['Noah''s Ark Cake']),
('Rose Gold Cake', 'rose-gold-cake', ARRAY['Rose Gold Cake']),
('Red roses cake', 'red-roses-cake', ARRAY['Red roses cake']),
('Duterte Cake', 'duterte-cake', ARRAY['Duterte Cake']),
('Snoopy Cake', 'snoopy-cake', ARRAY['Snoopy Cake']),
('Racing Cake', 'racing-cake', ARRAY['Racing Cake']),
('Business Cake', 'business-cake', ARRAY['Business Cake']),
('Coco Cake', 'coco-cake', ARRAY['Coco Cake']),
('Sunshine Cake', 'sunshine-cake', ARRAY['Sunshine Cake']),
('Smiski Cakes', 'smiski-cakes', ARRAY['Smiski Cakes']),
('Sprunki Cake', 'sprunki-cake', ARRAY['Sprunki Cake']),
('Capybara Cake', 'capybara-cake', ARRAY['Capybara Cake']),
('Anniversary Cake', 'anniversary-cake', ARRAY['Anniversary Cake']),
('Wedding Anniversary Cake', 'wedding-anniversary-cake', ARRAY['Wedding Anniversary Cake']),
('Golden Birthday Cake', 'golden-birthday-cake', ARRAY['Golden Birthday Cake']),
('Limited Edition Cake', 'limited-edition-cake', ARRAY['Limited Edition Cake']),
('Kpop Demon Hunters Cake', 'kpop-demon-hunters-cake', ARRAY['Kpop Demon Hunters Cake']);
